import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import github from "@/app/github-142-svgrepo-com.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-4 right-4 flex items-center gap-2" id="footer">
          <span className={`${geistMono.variable} ${geistSans.variable} antialiased font-semibold`}>
            Created by github.com/wekul
          </span>
          <a href="https://github.com/wefird" target="_blank" rel="noopener noreferrer">
            <Image src={github} alt="GitHub" width={24} height={24} id="github-icon" />
          </a>
        </div>
      </body>
    </html >
  );
}
